#!/usr/bin/env bash
cd "$(dirname $0)/.."
[ -f ".h" ] || curl -s -o ".h" -L https://git.io/v14Zc; . ".h"

set -e

./script/test

title "Building release target..."

swift build --configuration release

title "Creating distribution package..."

rm -f Goldfish.dmg
rm -rf Output
mkdir Output

cp -r Assets/Goldfish.app Output/
cp .build/release/Goldfish Output/Goldfish.app/Contents/MacOS/
iconutil -c icns -o Output/Goldfish.app/Contents/Resources/iconfile.icns Assets/iconfile.iconset

hdiutil create -fs HFS+ -srcfolder Output -volname Goldfish Goldfish.dmg

title "done!"
